import type {
  Property,
  Guest,
  Room,
  Booking,
  User,
  DashboardMetrics,
  OccupancyData,
  RevenueBySource,
} from './types'

export const properties: Property[] = [
  {
    id: 'prop-1',
    name: 'Grand Plaza Hotel',
    code: 'GPH',
    address: '123 Main Street',
    city: 'New York',
    country: 'USA',
    phone: '+1 (212) 555-0100',
    email: 'info@grandplaza.com',
    timezone: 'America/New_York',
    currency: 'USD',
    totalRooms: 150,
    createdAt: new Date('2020-01-15'),
  },
  {
    id: 'prop-2',
    name: 'Seaside Resort & Spa',
    code: 'SRS',
    address: '456 Ocean Drive',
    city: 'Miami',
    country: 'USA',
    phone: '+1 (305) 555-0200',
    email: 'info@seasideresort.com',
    timezone: 'America/New_York',
    currency: 'USD',
    totalRooms: 200,
    createdAt: new Date('2019-06-20'),
  },
  {
    id: 'prop-3',
    name: 'Mountain View Lodge',
    code: 'MVL',
    address: '789 Alpine Road',
    city: 'Aspen',
    country: 'USA',
    phone: '+1 (970) 555-0300',
    email: 'info@mountainviewlodge.com',
    timezone: 'America/Denver',
    currency: 'USD',
    totalRooms: 75,
    createdAt: new Date('2021-03-10'),
  },
]

export const guests: Guest[] = [
  {
    id: 'guest-1',
    title: 'Mr.',
    surname: 'Anderson',
    firstName: 'John',
    nationality: 'American',
    idPassportNumber: 'US123456789',
    numberOfAdults: 2,
    numberOfChildren: 0,
    childrenAges: [],
    otherAdult: {
      surname: 'Anderson',
      firstName: 'Mary',
      nationality: 'American',
      idPassportNumber: 'US987654321',
    },
    postalAddress: 'P.O. Box 1234',
    residentialAddress: '789 Oak Avenue',
    city: 'Chicago',
    stateProvince: 'Illinois',
    country: 'USA',
    telHome: '+1 (555) 123-4567',
    telBusiness: '+1 (555) 123-4568',
    cellphone: '+1 (555) 123-4569',
    email: 'john.anderson@email.com',
    dateIn: new Date('2025-01-27'),
    dateOut: new Date('2025-01-30'),
    roomNumber: '102',
    accountPayableBy: 'Guest',
    vehicleRegNo: 'IL-ABC-1234',
    breakfastTime: '08:00',
    preferences: {
      beef: true,
      pork: false,
      eggStyle: 'scrambled',
      dietaryRestrictions: ['Vegetarian'],
      specialRequests: ['Late check-out', 'Extra pillows'],
      roomType: 'suite',
      floorPreference: 'high',
      bedType: 'king',
    },
    serveDinner: true,
    agreedToTerms: true,
    signatureDate: new Date('2025-01-27'),
    loyaltyTier: 'gold',
    loyaltyPoints: 15420,
    totalStays: 12,
    totalSpent: 18500,
    tags: ['VIP', 'Business Traveler'],
    createdAt: new Date('2022-01-10'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'guest-2',
    title: 'Ms.',
    surname: 'Mitchell',
    firstName: 'Sarah',
    nationality: 'Canadian',
    idPassportNumber: 'CA987654321',
    numberOfAdults: 1,
    numberOfChildren: 0,
    childrenAges: [],
    postalAddress: '456 Maple Street',
    residentialAddress: '456 Maple Street',
    city: 'Toronto',
    stateProvince: 'Ontario',
    country: 'Canada',
    telHome: '+1 (416) 555-1234',
    telBusiness: '+1 (416) 555-5678',
    cellphone: '+1 (555) 234-5678',
    email: 'sarah.mitchell@email.com',
    dateIn: new Date('2025-01-26'),
    dateOut: new Date('2025-02-02'),
    roomNumber: '301',
    accountPayableBy: 'Corporate - Mitchell Corp',
    vehicleRegNo: '',
    breakfastTime: '07:30',
    preferences: {
      beef: true,
      pork: true,
      eggStyle: 'omelet',
      dietaryRestrictions: ['Gluten-free'],
      roomType: 'deluxe',
      floorPreference: 'any',
      bedType: 'queen',
    },
    serveDinner: false,
    agreedToTerms: true,
    signatureDate: new Date('2025-01-26'),
    loyaltyTier: 'platinum',
    loyaltyPoints: 52800,
    totalStays: 28,
    totalSpent: 45200,
    tags: ['Platinum Member', 'Anniversary Guest'],
    createdAt: new Date('2021-05-20'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: 'guest-3',
    title: 'Mr.',
    surname: 'Chen',
    firstName: 'Michael',
    nationality: 'American',
    idPassportNumber: 'DL789012345',
    numberOfAdults: 1,
    numberOfChildren: 0,
    childrenAges: [],
    postalAddress: '123 Tech Boulevard',
    residentialAddress: '123 Tech Boulevard, Apt 5B',
    city: 'San Francisco',
    stateProvince: 'California',
    country: 'USA',
    telHome: '+1 (415) 555-1234',
    telBusiness: '+1 (415) 555-5678',
    cellphone: '+1 (555) 345-6789',
    email: 'michael.chen@email.com',
    dateIn: new Date('2025-01-28'),
    dateOut: new Date('2025-01-31'),
    roomNumber: '302',
    accountPayableBy: 'Tech Solutions Inc.',
    vehicleRegNo: 'CA-XYZ-7890',
    breakfastTime: '06:30',
    preferences: {
      beef: true,
      pork: true,
      eggStyle: 'fried',
      specialRequests: ['Gym access', 'Business lounge'],
      roomType: 'executive',
      floorPreference: 'high',
      bedType: 'king',
    },
    serveDinner: true,
    agreedToTerms: true,
    signatureDate: new Date('2025-01-28'),
    loyaltyTier: 'silver',
    loyaltyPoints: 8200,
    totalStays: 6,
    totalSpent: 9800,
    tags: ['Corporate Account'],
    createdAt: new Date('2023-02-14'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: 'guest-4',
    title: 'Mrs.',
    surname: 'Williams',
    firstName: 'Emma',
    nationality: 'British',
    idPassportNumber: 'GB456789012',
    numberOfAdults: 2,
    numberOfChildren: 1,
    childrenAges: [8],
    otherAdult: {
      surname: 'Williams',
      firstName: 'James',
      nationality: 'British',
      idPassportNumber: 'GB456789013',
    },
    postalAddress: '10 Kensington Road',
    residentialAddress: '10 Kensington Road',
    city: 'London',
    stateProvince: 'Greater London',
    country: 'United Kingdom',
    telHome: '+44 20 7946 0958',
    telBusiness: '+44 20 7946 0959',
    cellphone: '+44 7700 900123',
    email: 'emma.williams@email.com',
    dateIn: new Date('2025-01-25'),
    dateOut: new Date('2025-02-01'),
    roomNumber: 'A102',
    accountPayableBy: 'Guest',
    vehicleRegNo: '',
    breakfastTime: '08:30',
    preferences: {
      beef: false,
      pork: false,
      eggStyle: 'boiled',
      dietaryRestrictions: ['No red meat'],
      specialRequests: ['Memory foam pillows', 'The Times newspaper'],
      roomType: 'suite',
      floorPreference: 'low',
      bedType: 'king',
    },
    serveDinner: true,
    agreedToTerms: true,
    signatureDate: new Date('2025-01-25'),
    loyaltyTier: 'gold',
    loyaltyPoints: 21350,
    totalStays: 15,
    totalSpent: 28900,
    tags: ['International', 'Spa Enthusiast'],
    createdAt: new Date('2022-08-05'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'guest-5',
    title: 'Mr.',
    surname: 'Martinez',
    firstName: 'David',
    nationality: 'Mexican',
    idPassportNumber: 'MX234567890',
    numberOfAdults: 2,
    numberOfChildren: 2,
    childrenAges: [5, 10],
    otherAdult: {
      surname: 'Martinez',
      firstName: 'Rosa',
      nationality: 'Mexican',
      idPassportNumber: 'MX234567891',
    },
    postalAddress: '567 Sunset Avenue',
    residentialAddress: '567 Sunset Avenue',
    city: 'Los Angeles',
    stateProvince: 'California',
    country: 'USA',
    telHome: '+1 (310) 555-1234',
    telBusiness: '',
    cellphone: '+1 (555) 456-7890',
    email: 'david.martinez@email.com',
    dateIn: new Date('2025-01-27'),
    dateOut: new Date('2025-01-29'),
    roomNumber: 'C2',
    accountPayableBy: 'Guest',
    vehicleRegNo: 'CA-MART-2025',
    breakfastTime: '09:00',
    preferences: {
      beef: true,
      pork: true,
        eggStyle: 'scrambled',
          roomType: 'deluxe',
          floorPreference: 'any',
          bedType: 'queen',
    },
    serveDinner: true,
    agreedToTerms: true,
    signatureDate: new Date('2025-01-27'),
    loyaltyTier: 'bronze',
    loyaltyPoints: 2100,
    totalStays: 3,
    totalSpent: 2850,
    tags: ['New Member'],
    createdAt: new Date('2024-06-18'),
    updatedAt: new Date('2025-01-08'),
  },
  {
    id: 'guest-6',
    title: 'Miss',
    surname: 'Thompson',
    firstName: 'Lisa',
    nationality: 'American',
    idPassportNumber: 'US-DL-1234567',
    numberOfAdults: 1,
    numberOfChildren: 0,
    childrenAges: [],
    postalAddress: '890 College Street',
    residentialAddress: '890 College Street, Dorm 3B',
    city: 'Boston',
    stateProvince: 'Massachusetts',
    country: 'USA',
    telHome: '',
    telBusiness: '',
    cellphone: '+1 (555) 567-8901',
    email: 'lisa.thompson@email.com',
    dateIn: new Date('2025-01-28'),
    dateOut: new Date('2025-01-30'),
    roomNumber: '101',
    accountPayableBy: 'Guest',
    vehicleRegNo: '',
    breakfastTime: '10:00',
    preferences: {
      beef: true,
      pork: false,
      eggStyle: 'omelet',
        roomType: 'standard',
        bedType: 'twin',
    },
    serveDinner: false,
    agreedToTerms: true,
    signatureDate: new Date('2025-01-28'),
    loyaltyTier: 'bronze',
    loyaltyPoints: 850,
    totalStays: 2,
    totalSpent: 980,
    tags: ['Student Discount'],
    createdAt: new Date('2024-11-02'),
    updatedAt: new Date('2025-01-12'),
  },
]

export const rooms: Room[] = [
  // Grand Plaza Hotel rooms
  { id: 'room-1', propertyId: 'prop-1', number: '101', floor: 1, type: 'standard', status: 'available', maxOccupancy: 2, baseRate: 150, amenities: ['WiFi', 'TV', 'Mini-bar'], lastCleaned: new Date() },
  { id: 'room-2', propertyId: 'prop-1', number: '102', floor: 1, type: 'standard', status: 'occupied', maxOccupancy: 2, baseRate: 150, amenities: ['WiFi', 'TV', 'Mini-bar'], lastCleaned: new Date() },
  { id: 'room-3', propertyId: 'prop-1', number: '201', floor: 2, type: 'deluxe', status: 'available', maxOccupancy: 3, baseRate: 250, amenities: ['WiFi', 'TV', 'Mini-bar', 'Balcony'], lastCleaned: new Date() },
  { id: 'room-4', propertyId: 'prop-1', number: '202', floor: 2, type: 'deluxe', status: 'cleaning', maxOccupancy: 3, baseRate: 250, amenities: ['WiFi', 'TV', 'Mini-bar', 'Balcony'], lastCleaned: new Date() },
  { id: 'room-5', propertyId: 'prop-1', number: '301', floor: 3, type: 'suite', status: 'occupied', maxOccupancy: 4, baseRate: 450, amenities: ['WiFi', 'TV', 'Mini-bar', 'Balcony', 'Jacuzzi'], lastCleaned: new Date() },
  { id: 'room-6', propertyId: 'prop-1', number: '302', floor: 3, type: 'suite', status: 'reserved', maxOccupancy: 4, baseRate: 450, amenities: ['WiFi', 'TV', 'Mini-bar', 'Balcony', 'Jacuzzi'], lastCleaned: new Date() },
  { id: 'room-7', propertyId: 'prop-1', number: '401', floor: 4, type: 'executive', status: 'available', maxOccupancy: 2, baseRate: 350, amenities: ['WiFi', 'TV', 'Mini-bar', 'Office desk', 'Lounge access'], lastCleaned: new Date() },
  { id: 'room-8', propertyId: 'prop-1', number: '501', floor: 5, type: 'penthouse', status: 'maintenance', maxOccupancy: 6, baseRate: 850, amenities: ['WiFi', 'TV', 'Mini-bar', 'Kitchen', 'Terrace', 'Butler service'], lastCleaned: new Date() },
  // Seaside Resort rooms
  { id: 'room-9', propertyId: 'prop-2', number: 'A101', floor: 1, type: 'standard', status: 'available', maxOccupancy: 2, baseRate: 180, amenities: ['WiFi', 'TV', 'Ocean view'], lastCleaned: new Date() },
  { id: 'room-10', propertyId: 'prop-2', number: 'A102', floor: 1, type: 'deluxe', status: 'occupied', maxOccupancy: 3, baseRate: 280, amenities: ['WiFi', 'TV', 'Ocean view', 'Balcony'], lastCleaned: new Date() },
  // Mountain View Lodge rooms
  { id: 'room-11', propertyId: 'prop-3', number: 'C1', floor: 1, type: 'standard', status: 'available', maxOccupancy: 2, baseRate: 120, amenities: ['WiFi', 'TV', 'Fireplace'], lastCleaned: new Date() },
  { id: 'room-12', propertyId: 'prop-3', number: 'C2', floor: 1, type: 'suite', status: 'occupied', maxOccupancy: 4, baseRate: 320, amenities: ['WiFi', 'TV', 'Fireplace', 'Hot tub'], lastCleaned: new Date() },
]

export const bookings: Booking[] = [
  {
    id: 'booking-1',
    propertyId: 'prop-1',
    guestId: 'guest-1',
    roomId: 'room-2',
    checkIn: new Date('2025-01-27'),
    checkOut: new Date('2025-01-30'),
    status: 'checked_in',
    adults: 1,
    children: 0,
    source: 'direct',
    totalAmount: 450,
    paidAmount: 450,
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-27'),
  },
  {
    id: 'booking-2',
    propertyId: 'prop-1',
    guestId: 'guest-2',
    roomId: 'room-5',
    checkIn: new Date('2025-01-26'),
    checkOut: new Date('2025-02-02'),
    status: 'checked_in',
    adults: 2,
    children: 0,
    source: 'booking.com',
    totalAmount: 3150,
    paidAmount: 1500,
    specialRequests: 'Anniversary celebration - please arrange flowers',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-26'),
  },
  {
    id: 'booking-3',
    propertyId: 'prop-1',
    guestId: 'guest-3',
    roomId: 'room-6',
    checkIn: new Date('2025-01-28'),
    checkOut: new Date('2025-01-31'),
    status: 'confirmed',
    adults: 1,
    children: 0,
    source: 'direct',
    totalAmount: 1350,
    paidAmount: 675,
    specialRequests: 'Early check-in requested',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'booking-4',
    propertyId: 'prop-2',
    guestId: 'guest-4',
    roomId: 'room-10',
    checkIn: new Date('2025-01-25'),
    checkOut: new Date('2025-02-01'),
    status: 'checked_in',
    adults: 2,
    children: 1,
    source: 'expedia',
    totalAmount: 1960,
    paidAmount: 1960,
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: 'booking-5',
    propertyId: 'prop-3',
    guestId: 'guest-5',
    roomId: 'room-12',
    checkIn: new Date('2025-01-27'),
    checkOut: new Date('2025-01-29'),
    status: 'checked_in',
    adults: 2,
    children: 0,
    source: 'airbnb',
    totalAmount: 640,
    paidAmount: 640,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-27'),
  },
]

export const users: User[] = [
  {
    id: 'user-1',
    email: 'admin@omnihotel.com',
    name: 'Alex Johnson',
    role: 'admin',
    propertyIds: ['prop-1', 'prop-2', 'prop-3'],
    avatar: undefined,
    lastLogin: new Date('2025-01-28'),
    isActive: true,
  },
  {
    id: 'user-2',
    email: 'manager@grandplaza.com',
    name: 'Maria Garcia',
    role: 'manager',
    propertyIds: ['prop-1'],
    avatar: undefined,
    lastLogin: new Date('2025-01-28'),
    isActive: true,
  },
  {
    id: 'user-3',
    email: 'frontdesk@grandplaza.com',
    name: 'James Wilson',
    role: 'front_desk',
    propertyIds: ['prop-1'],
    avatar: undefined,
    lastLogin: new Date('2025-01-28'),
    isActive: true,
  },
]

export const dashboardMetrics: DashboardMetrics = {
  occupancyRate: 78.5,
  occupancyChange: 5.2,
  revenue: 125400,
  revenueChange: 12.3,
  arrivalsToday: 8,
  departuresToday: 5,
  averageRate: 285,
  averageRateChange: 3.8,
  guestsInHouse: 42,
  availableRooms: 32,
  pendingCheckIns: 3,
  pendingCheckOuts: 2,
}

export const occupancyData: OccupancyData[] = [
  { date: '2025-01-22', occupancy: 72, revenue: 18500 },
  { date: '2025-01-23', occupancy: 75, revenue: 19200 },
  { date: '2025-01-24', occupancy: 78, revenue: 21000 },
  { date: '2025-01-25', occupancy: 82, revenue: 22800 },
  { date: '2025-01-26', occupancy: 85, revenue: 24100 },
  { date: '2025-01-27', occupancy: 79, revenue: 20500 },
  { date: '2025-01-28', occupancy: 78, revenue: 19300 },
]

export const revenueBySource: RevenueBySource[] = [
  { source: 'Direct', amount: 52000, percentage: 41.5 },
  { source: 'Booking.com', amount: 35000, percentage: 27.9 },
  { source: 'Expedia', amount: 22000, percentage: 17.5 },
  { source: 'Airbnb', amount: 10400, percentage: 8.3 },
  { source: 'Walk-in', amount: 6000, percentage: 4.8 },
]

// Helper functions for fuzzy matching
export function searchGuests(query: string): Guest[] {
  const lowerQuery = query.toLowerCase()
  return guests.filter(
    (guest) =>
      guest.firstName.toLowerCase().includes(lowerQuery) ||
      guest.surname.toLowerCase().includes(lowerQuery) ||
      guest.email.toLowerCase().includes(lowerQuery) ||
      guest.cellphone.includes(query) ||
      guest.idPassportNumber.toLowerCase().includes(lowerQuery)
  )
}

export function getGuestById(id: string): Guest | undefined {
  return guests.find((g) => g.id === id)
}

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id)
}

export function getRoomsByProperty(propertyId: string): Room[] {
  return rooms.filter((r) => r.propertyId === propertyId)
}

export function getBookingsByProperty(propertyId: string): Booking[] {
  return bookings.filter((b) => b.propertyId === propertyId)
}

export function getGuestBookings(guestId: string): Booking[] {
  return bookings.filter((b) => b.guestId === guestId)
}
